<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/headerStyle.css">
    <link rel="stylesheet" href="/css/bannerStyle.css">
    <link rel="stylesheet" href="/css/homeStyle.css">
    <link rel="stylesheet" href="/css/listNewsStyle.css">
    <link rel="stylesheet" href="/css/detailStyle.css">
    <link rel="stylesheet" href="/css/footerStyle.css">

    <title>Document</title>
</head>

<body>

    <header class="header">
        <a class="header_info" href="/news/">
            <img class="header_info_icon" src="/uploads/icons/logo 1.svg">
            <p class="header_info_headline">ГАЛАКТИЧЕСКИЙ </br> ВЕСТНИК</p>
        </a>
    </header>

    <?php
        echo $content;
    ?>

    <footer class="footer">
        <div class="footer-line"></div>
        <p class="footer-info">© 2023 — 2412 «Галактический вестник»</p>
    </footer>
</body>

</html>