<?php
use Core\Route;

$routesArray = Route::$routes['HomeRouter'];
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/pageNotFoundStyle.css">
    <title>Document</title>
</head>

<body>
    <div class="page_not_found">
        <h1 class="page_not_found_headline">PAGE NOT FOUND</h1>
        <h1 class="page_not_found_headline">404</h1>
        <a href=<?= $routesArray->getHomeUrl() ?> class="page_not_found_back_page">
            <img class="arrow_back_page" src="/uploads/icons/arrow-back-page.png">
            Вернуться на главную
        </a>
    </div>
</body>

</html>